### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by abinashmeher999** [Jd007/ebs-consistent-snapshot#1]
Hello.

Thanks for creating this script! After trying to get the perl version working, you have no idea how glad I am to find this repo. I wanted to use some part of the code in my own snippet and that is when I saw that their is no license file. From https://help.github.com/articles/licensing-a-repository/
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

It would be great if you could license this under an appropriate license.

**Comment by Jd007** [comment]
Sorry for the late response, I saw this and forgot to follow up. I will look into adding a license, but for now feel free to use the code, I will be looking for the least restrict OSS license to add to it. Thanks.

**Comment by Jd007** [comment]
License file added.

**Comment by abinashmeher999** [comment]
Thanks a lot! :)
